"""create Blog table, update Show table

Revision ID: 59758d58260b
Revises: 76776238e34d
Create Date: 2023-07-15 11:41:06.665464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59758d58260b'
down_revision = '76776238e34d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_posts')
    # ### end Alembic commands ###
